### ISSUE TITLE
Unit test for redux business logic

### ISSUE THREAD

**Issue by togonow** [tur-nr/polymer-redux#104]
Is it possible to do business logic on redux without getting using polymer fixture since it's a very lenghty process.
I'm trying to achieve like the following post 
https://hackernoon.com/redux-testing-step-by-step-a-simple-methodology-for-testing-business-logic-8901670756ce

the tests are very straight to the point and focus on the state instead of polymer elements.

Thanks in advance.

**Comment by tur-nr** [comment]
I think it boils down to how your app is structured. Everything Redux within a Polymer app can be completely separate.

_store.js_
```js
import { createStore, combineReducers } from 'redux';
import {
    UPDATE_FOO,
    UPDATE_BAR
} from './actions';
import * as reducers from './reducers';

export default createStore(combineReducers(reducers));
```

_reducers.js_
```js
export function foo(state, action) {
    switch (action.type) {
        case UPDATE_FOO:
            return Object.assign({}, state, {
                foo: action.foo,
            });
        
        default:
            return state;
    }
}

export function bar(state, action) {
    switch (action.type) {
        case UPDATE_BAR:
            return Object.assign({}, state, {
                bar: 'bar',
            });
        
        default:
            return state;
    }
}
```

_actions.js_
```js
export const UPDATE_FOO = 'UPDATE_FOO';
export const UPDATE_BAR = 'UPDATE_BAR';

export function updateFoo(foo) {
    return {
        foo,
        type: UPDATE_FOO,
    };
}

export function updateBar(bar) {
    return {
        bar,
        type: UPDATE_BAR,
    };
}
```

_selectors.js_
```js
export function selectFoo(state) {
    return state.foo;
}

export function selectBar(state) {
    return state.bar;
}
```

_redux-mixin.js_
```js
import PolymerRedux from 'polymer-redux';
import store from './store';

export default ReduxMixin(store);
```

_my-element.js_
```js
import Polymer from 'polymer';
import ReduxMixin from './redux-mixin';
import {
    updateFoo,
    updateBar
} from './actions';
import {
    selectFoo,
    selectBar
} from './selectors';

export default class MyElement extends ReduxMixin(Polymer.Element) {
    static get is() {
        return 'my-element';
    }

    static get properties() {
        return {
            foo: {
                type: String,
                statePath: selectFoo,
            },
            bar: {
                type: String,
                statePath: selectBar,
            },
        };
    }

    static get actions() {
        return {
            updateFoo,
            updateBar,
        };
    }
}
```

With the above structure your Mixin is nothing more than a function call to PolymerRedux. Your Element just imports the actions. Now all your Redux logic has be decoupled from Polymer ready for you to test.

**Comment by togonow** [comment]
1. can u use import with polymer?? or is there a way to transpile? 
2. I'm already able to import reduxmixinto all my app polymer element along with actions to polymer elements, so are you suggesting creating one polymer element that have access to all the redux state and actions and do the tests on that element like any other polymer element? or i mis understood?

Thanks

**Comment by tur-nr** [comment]
It was pseudo code really, but you can achieve it with transpilation. Google polmer and babel to know how.

You would test each file much like the article says. I have separated out the Redux logic from Polymer so you can test the business side of your _store_, _actions_ and  _selectors_. Then you would go ahead and only do the Polymer fixture for your `my-element.js`. If you didn't want the ReduxMixin in your element you could easily do the following.

_my-element.js_
```js
import Polymer from 'polymer';

export default class MyElement extends Polymer.Element {
    static get is() {
        return 'my-element';
    }

    static get properties() {
        return {
            foo: {
                type: String,
            },
            bar: {
                type: String,
            },
        };
    }

    // business logic here
}
```

_connected-element.js_
```js
import MyElement from './my-element';
import ReduxMixin from './redux-mixin';
import {
    updateFoo,
    updateBar
} from './actions';
import {
    selectFoo,
    selectBar
} from './selectors';

export default class ConnectedElement extends ReduxMixin(MyElement) {
    static get is() {
        return 'connected-element';
    }

    static get properties() {
        return {
            foo: {
                type: String,
                statePath: selectFoo,
            },
            bar: {
                type: String,
                statePath: selectBar,
            },
        };
    }

    static get actions() {
        return {
            updateFoo,
            updateBar,
        };
    }

    // nothing here, just binding
}
```

Now you put your business logic into `my-element` and test it without Redux. Then the `connected-element` does the bindings and that's it.

**Comment by togonow** [comment]
I'm following up to "Now you put your business logic into my-element and test it without Redux. Then the connected-element does the bindings and that's it."  but it's almost midnight here, will look at it more tomorrow. Thanks

**Comment by tur-nr** [comment]
Any progress on this?

**Comment by togonow** [comment]
Haven't had a chance to look at it! won't be back for another week
