### ISSUE TITLE
Persisting Redux Store on Page Refresh

### ISSUE THREAD

**Issue by steltz** [tur-nr/polymer-redux#116]
Can someone point me in the right direction to enable persisting the store on page refresh. I've looked through all the issues and found issue #31, but I'm still unsure how to implement this.

Any pointers are greatly appreciated, thank you.

**Comment by tur-nr** [comment]
Take a look at https://github.com/rt2zz/redux-persist

**Comment by tur-nr** [comment]
Not an issue with the library, implementation question.
