### ISSUE TITLE
Polymer observer workflow not triggered for Redux actions on Array properties

### ISSUE THREAD

**Issue by stefanreimers** [tur-nr/polymer-redux#12]
When using Array properties for the Polymer-Redux binding, state changes are not correctly reflected in the component. The property value is changed correctly but Polymers observer workflow is not triggered to reflect the changes in the template. See code below:

index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Polymer-Redux Example</title>
    
  <script src="./bower_components/webcomponentsjs/webcomponents.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/redux/3.5.2/redux.min.js"></script>
  <link rel="import" href="./bower_components/polymer-redux/polymer-redux.html">

  <!-- Load store -->
  <script>
    var initialState = {
      users: []
    };
    store = Redux.createStore(function(state=initialState, action) {

      switch(action.type){
        
        case 'USER_ADD':
          var newState = Object.assign({}, state);
          newState.users.push(action.user);
          return newState;
          break;
          
        default:
          return state;
      }
    });
    var ReduxBehavior = new PolymerRedux(store);
  </script>
  <!-- Custom elements -->
  <link rel="import" href="elements/MyElement.html">

</head>
<body>

  <!-- App -->
  <my-element id="my"></my-element>

  <script>
    var insertUser = function( user ){
      store.dispatch({
        type: 'USER_ADD',
        user: user
      });
    }
    store.subscribe( () => {
      console.log('state updated');
    });
    var my = document.getElementById('my');
  </script>
</body>
</html>
```

MyElement.html
```html
<link rel="import" href="../bower_components/polymer/polymer.html">

<dom-module id="my-element">
  <template>
    
    <div>{{computeFirst(users.*,0)}}</div>
    
    <ul>
      <template is="dom-repeat" items="[[users]]">
        <li>{{item.name}}</li>
      </template>
    </ul>
  </template>

  <script>
    Polymer({

      is: 'my-element',
      
      behaviors: [ ReduxBehavior ],
      
      properties: {
        
        users: {
          type: Array,
          value: () => [],
          statePath: 'users',
          observer: '_handleUser'
        }
        
      },
      
      observers: [
        'usersChanged(users.*)', 
        'userAddedOrRemoved(users.splices)'
      ],
      
      // Observer defined in property itself
      _handleUser: function(newValue, oldValue){
        console.log('_handleUser', newValue, oldValue);
      },
      
      // Observers defined outside of property (I)
      usersChanged: function(users){
        console.log('usersChanged', users);
      },
      
      // Observers defined outside of property (II)
      userAddedOrRemoved: function(changeRecord){
        console.log('userAddedOrRemoved', changeRecord);
      },

      // Computed binding
      computeFirst: function(changeRecord, idx){
        return (changeRecord.base[idx])?changeRecord.base[idx].name:'';
      },

      // Manipulation method
      addUser: function(user) {
        this.unshift('users', user);
      }

    });
  </script>
</dom-module>
```

State of the property can be checked with `my.users`. Those are possible manipulations that are reflected in the template:

* `my.users = [{name: 'Eric', age: 36}, {name: 'Mark', age: 27}, {name: 'Frank', age: 29}]`
* `my.addUser({name: 'John', age:18})`

The browser console shows that those method calls trigger one/multiple observers or the computed binding. But inserting data via the redux store with `insertUser({name: 'Wilhelm', age: 72});` does not.

I guess the reason for that is how Polymer handles observing array mutations. It supplies array manipulation methods that guarantee that observer workflows are triggered. Imho the binding has to hook into that workflow as well.

So far: great work!

**Comment by tur-nr** [comment]
Nice 🐞 

I have a fix for this by updating Polymer to 1.5 so that I can make use of `Polymer.ArraySplice.calculateSplices` and altered the way it sets properties and notifies Polymer.

There is an issue with your case you supplied. The element's `addUser` method, you are modifying the array outside of the Redux 😱 I hope this was just to demonstrate the natural Polymer observe? If your property uses PolymerRedux behaviour then you should **ALWAYS** dispatch an action to modify the state. Otherwise your components and state will get out of sync. I have no known way to stop Polymer modifying the property once using PolymerRedux so it's up to the developer. I should write a caveat in the read me documenting this.

Thanks for the submission, so glad people are actively using this, great to see. I will try and get the fix in some time this evening if not tomorrow (Australia/Sydney).

**Comment by Schibum** [comment]
Just ran into the same issue and would appreciate a fix, too.

**Comment by tur-nr** [comment]
Check out the array examples.

**Comment by Schibum** [comment]
Thx. 
BTW, I just pushed some boilerplate skeleton for using polymer-redux based on polymer-starter kit here:  https://github.com/Schibum/polymer-redux-starter-kit
