### ISSUE TITLE
Is it possible to call mapStateToProps from a mixin?

### ISSUE THREAD

**Issue by fekitibi** [tur-nr/polymer-redux#141]
I have the redux-todo component which connects the todoApp with the redux store. I also created a mixin from where I would like to inherit some properties and at the same time I would like to connect one of this property to the store from the mixin. I manage to call the mapStateToProps method from the mixin but unfortunately it never bind the property to the store.

Here is what I have so far:

**redux-todo.js:**

    import TodoApp from 'todo-app';
    import ReduxMixin from 'mixins/redux';
    import { bindActionCreators } from 'polymer-redux';
    import { AnotherMixin } from 'another-mixin.js';
    import { ExtraMixin } from 'extra-mixin.js';
    
    class ReduxTodo extends AnotherMixin(ExtraMixin(ReduxMixin(TodoApp))) {
    	/**
    	 * We map any redux state to the element properties here. Feel free to use
    	 * libraries like reselect to improve the performance of your app.
    	 *
    	 * @param {object} state The redux state object.
    	 * @param {HTMLElement} element The element instance.
    	 *
    	 * @return {Object} Key-value map of properties and their values.
    	 */
    
    	static get properties() {
    		super.properties;
    	}
    
    	static mapStateToProps(state, element) {
    		super.mapStateToProps(state);
    		console.log('mapping props');
    		console.dir(state);
    		console.dir(this);
    		return {
    			tasks: state.tasks,
    			extras: state.extras,//from extras mixin
    			//another: state.another
    		};
    	}
    
    	constructor(){
    		super();
    		console.log(this.extras);
    		console.log(this.another);
    	}
    
    	ready() {
    		super.ready();
    		// do something that requires access to the shadow tree
    		console.log(this.extras);
    		console.log(this.another);
    		console.log(this.tasks);
    		//console.log(this.mapStateToProps);
    		;
    	  }
    
    
    	/**
    	 * Mapping dispatch to CustomEvents that bubble from internal elements.
    	 * This is only called once so make sure you bind correctly.
    	 *
    	 * Use the exported helper `bindActionCreators` to construct a key-value map
    	 * of events that will call `dispatch` with the returning value.
    	 *
    	 * @param {Function} dispatch The redux dispatch function.
    	 * @param {HTMLElement} element The element instance.
    	 *
    	 * @return {Object} Key-value map of event names and their listeners.
    	 */
    	static mapDispatchToEvents(dispatch, element) {
    		return bindActionCreators(
    			{
    				addTask(event) {
    					return {
    						type: 'ADD_TASK',
    						task: event.detail
    					};
    				},
    				updateTaskDone(event) {
    					return {
    						type: 'UPDATE_TASK_DONE',
    						index: event.detail.index,
    						done: event.detail.done
    					};
    				},
    				removeTask(event) {
    					return {
    						type: 'REMOVE_TASK',
    						index: event.detail
    					};
    				}
    			},
    			dispatch
    		);
    	}
    }
    
    customElements.define('redux-todo', ReduxTodo);

**another-mixin.js:**

    import {dedupingMixin} from '@polymer/polymer/lib/utils/mixin.js';
    import ReduxMixin from 'mixins/redux';
    
    let internalAnotherMixin = (base) =>
      class extends ReduxMixin(base) {
        static get properties() {
    		return {
    			another:{
                    type:Boolean,
                    value: true
                } 
    		};
        }
        constructor(){
            super();
            console.log("Hello from another constructor");
            //this.another = true;
        }
    
        static mapStateToProps(state, element) {
            console.log('mapping props from another-mixin');
            console.dir(this);
            console.dir(state);
    		return {
    			another: state.another
    		};
    	}
    
      }
    
      export const AnotherMixin = dedupingMixin(internalAnotherMixin);

**extra-mixin.js:**

    import {dedupingMixin} from '@polymer/polymer/lib/utils/mixin.js';
    
    let internalExtraMixin = (base) =>
      class extends base {
        static get properties() {
    		return {
    			extras: String
    		};
        }
        constructor(){
            super();
            console.log("Hello from extras constructor");
            //this.extras = "Hello world";
        }
      }
    
      export const ExtraMixin = dedupingMixin(internalExtraMixin);

**Comment by tur-nr** [comment]
I think you got a little bit of redux mixing inception going on here. From my understanding, you have a mixin (another) and you wish to wrap your redux-todo element (also wrapped with redux) with it. Another has a property that is binding to the redux store and you want to use that property within the redux-todo. Is there a specific reason why Another needs to be wrapped in redux?

Why don't you just promote the property to the redux-todo connector element?

**Comment by fekitibi** [comment]
Hi I just figured that out as well I modified the code and removed the extra ReduxMixin from the redux-todo.js since it is inheriting it from the another-mixin I dont really need to put it in todo :)

**Here is my change:**
```
...
class ReduxTodo extends AnotherMixin(ExtraMixin((TodoApp))) {
...
}
```
Or I could just leave the ReduxMixin inside the redux-todo.js and remove them from the mixins since they are inheriting from each other it should work :) (as far as I understand it correctly)

And the reason why I want to have it in my mixin is that if I map the props inside in this case the redux-todo.js it is fine but what if I want to use this mixin on a lot of component in that case I would have to write the mapStateToProps() in all of the components. I was just wondering if it would be possible just to map this inherited prop directly from a mixin.

**Comment by tur-nr** [comment]
I would strongly recommend don't use inheritance for passing around properties from redux. There is a library called [reselect ](https://github.com/reduxjs/reselect) that you can use to create all your selectors as pure, testable functions. Then its perfectly ok to write your `mapStateToProps` multiple times.

**redux-todo.js**
```js
import { getAnother, getTasks } from './selectors';

class ReduxTodo extends ReduxMixin(TodoApp) {
    static mapStateToProps(state, element) {
        return {
            tasks: getTasks(state),
            another: getAnother(state),
            // The following is completely useless but demos you
            // can still access the elements inherited properties
            extra: element.extra,
        };
    }
}
```

**another-mixin.js**
```js
import { getAnother } from './selectors';

export default Base => class extends ReduxMixin(Base) {
    static mapStateToProps(state, element) {
        return {
            another: getAnother(state),
        };
    }
}
```

Notice how I reuse the `getAnother` selector. It's perfectly fine that `Another` mixin and `ReduxTodo` each have a defined `static mapStateToProps`. This should remove the need for inheritance and also wrapping too many mixins.

**Comment by fekitibi** [comment]
Thank you I will look into this library :)

**Comment by fekitibi** [comment]
I made an example maybe I am missing something but my mapStateToProps function is still not working inside my mixin.

Here is my code:

**redux-todo.js:**

```
import TodoApp from '../elements/todo-app';
import ReduxMixin from '../mixins/redux';
import { AnotherMixin } from './another-mixin.js';
import { TaskSelector} from './selectors.js'

class ReduxTodo extends AnotherMixin(ReduxMixin(TodoApp)) {
    static mapStateToProps(state, element) {
        return {
            tasks: TaskSelector(state),
        };
    }
    ready() {
	super.ready();
	console.log(this.another); // undefined
	console.log(this.tasks); // I am getting this one correctly
  }
}
customElements.define('redux-todo', ReduxTodo);
```

**another-mixin.js:**

```
import {dedupingMixin} from '@polymer/polymer/lib/utils/mixin.js';
import { AnotherSelector} from './selectors.js'

let internalAnotherMixin = (base) =>
  class extends base {
    constructor(){
        super();
        console.log("Hello from another constructor");
        //this.another = true;
    }

    // this mapStateToProps is never getting called
    static mapStateToProps(state, element) {
      return {
        another: AnotherSelector(state)
      };
    }

  }

  export const AnotherMixin = dedupingMixin(internalAnotherMixin);
```

**selectors.js:**

```
import { createSelector } from 'reselect'

const getAnother = state => state.another;
const getTasks = state => state.tasks;

export const AnotherSelector = createSelector(
    getAnother,
    items => items
  );
  
export const TaskSelector = createSelector(
    getTasks,
    items => items
  );
```

I tried to make my selectors as simple as I could maybe I missed something there.

**Comment by tur-nr** [comment]
I don't understand why you are trying to make `ReduxTodo` inherit from `AnotherMixin`? What benefit is `AnotherMixin` giving you that selectors can not? Move the `another` property up to `ReduxTodo` and reuse the selector.

**Comment by tur-nr** [comment]
Also, say I want to use `AnotherMixin` with another **_non_** redux connected element. `static mapStateToProps` will never work

**Comment by fekitibi** [comment]
What I am thinking if you have a mixin which has some props and some methods which you want to inherit from some of your components and you have props from the mixin which you want to connect to store as I get it from you I cant really do that. If I am getting right what I should do is to create selectors for the props what I want to connect. I will be still able to pass the code what I want to share through mixins but I would not use them to bind props to store.

I was just curious if I could put everything into a mixin because lets say I have 30 components which are using my mixin in this case if I could do the binding in the mixin I would not have to do it 30 times in each components, but if this is not the proper way to do it, then okay I acknowledged it and thank you for your help :)

**Comment by craPkit** [comment]
@fekitibi I see where you're coming from. I'm using the same approach for sharing store/prop bindings between different components, but this discussion made me question that.

Anyway, regarding your original question:
When you (re-)define `mapStateToProps` in a mixin _and_ its "subclass", the latter will override the former. To work around that, you could join the subclass' result with that of the mixin:

**redux-todo.js**
```JavaScript
static mapStateToProps(state, element) {
  return Object.assign({}, super.mapStateToProps(...arguments), {
    ...subClassPropsMappings
  });
}
```
**another-mixin.js**
```JavaScript
static mapStateToProps(state, element) {
  return {
    ...mixinPropsMappings
  };
}
```

Obviously this would need to be implemented in each subclass. Alternatively, you could pass your subclass mappings to the mixin, as a parameter.

**redux-todo.js**
```JavaScript
class extends AnotherMixin(TodoApp, (state, element) => ({
  ...subClassPropsMappings
})) {
  // ...
}
```

**another-mixin.js**
```JavaScript
export const AnotherMixin = (base, addParamMappings = () => ({})) => class extends base {
  // ...
  static mapStateToProps(state, element) {
    return Object.assign({}, {
      ...subClassProps
    }, addParamMappings(...arguments));
  }
  // ...
}
```

While this has an off-standard look, I prefer the latter approach, since it delegates mixing in the properties to the, well, mixin.

If you're working with classical inheritance, the former method might be easier to implement, especially since you can override the method more than once, over multiple hierarchical levels.

**Comment by craPkit** [comment]
@tur-nr I think this should not be a discussion whether inheritance or composition is better.
Instead, if you want to provide an un-opinionated library, the question should be: how does the toolkit your library is targeting implement similar concepts?

`properties` are a good example: they are defined almost exactly the same way as `mapStateToProps` (even though the static non-getter of the latter allows for more customization), and also return a quasi-map. Used in an inheritance-based object model, however, overriding the getter for `properties` will always _add to the existing_ properties map, never _override_ that of the mixin or base class.
That way it doesn't matter if I inherit or compose my functionality—both will work _identically_.
For me it's a matter of code consistency!

Things get worse if I'm upgrading from a previous verison of polymer-redux (along with its `statePath` syntax): Now I have to move all my existing mappings from the base classes (which were once passed down along with their respective properties) and duplicate them to every child class (or implement my rather obscure work-around, everywhere).
