### ISSUE TITLE
How to use Redux selectors?

### ISSUE THREAD

**Issue by ronnyroeller** [tur-nr/polymer-redux#16]
`polymer-redux` is a great library! One thing that isn't clear to me though: How would one use Redux selectors with Polymer data binding?

For example: For a store with normalized state shape (https://egghead.io/lessons/javascript-redux-normalizing-the-state-shape) -> how would I bind the outcome of the selector that denormalizes the data? In Dan's todo example (which he talks about in the video): How to bind to `getAllTodos()`, which would inform Polymer whenever the IDs change or the data of a todo itself?

**Comment by tur-nr** [comment]
Polymer Redux is relatively new. I haven't worked it into an actual
application as of yet. The way it's connected to polymer is only by state,
how you write your Redux reducers, construct your application state, and
dispatch actions has no correlation to Polymer Redux.

I would like to add more examples to the library. Perhaps if you could
demonstrate a store and reducer and we can both work out how Polymer Redux
can handle normalised data. I've watched the video and it seems like the
stores state changes to managing ids rather than arrays. It may mean that
you have to bind properties to another state path, or use a computed
property in your Polymer element to construct the result you're looking for
in the stores state.

Let's get another example, this could be good in defining a best practice :)

**Comment by cvanleeuwen** [comment]
One option is to use `statePath` in combination with a function;

```
properties: {
    _allTodos: {
        type: Array,
        statePath: function (state) {
            return todos.selectors.getAllTodos(state);
        }
    },
}
```

You can also use any properties from your element (this = current polymer element). Just make sure to use `function(state) { ... }` and not `(state) => { ... }`

**Comment by ronnyroeller** [comment]
Thanks for your input.
We experimented with different approaches during the last days. I compiled all our learnings into a blog post: https://medium.com/collaborne-engineering/selectors-in-polymer-redux-c423007261f3#.3oi2cb1gn

**Comment by tur-nr** [comment]
Hey, I read your articles, really appreciate your thoughts. I like the idea of selectors, it gives the element a little bit more flexibility on using the state.

Take the following element for example:

```javascript
Polymer({
  behaviors: [ ReduxBehavior ],
  properties: {
    _todos: {
      type: Array,
      statePath: 'todos'
    },
    _filter: {
      type: String,
      statePath: "filterType"
    },
    todos: {
      type: Array,
      computed: '_filteredTodos(_todos, _filter)'
    },
    total: {
      type: Number,
      computed: '_totalTodos(_todos)'
    }
  },
  _totalTodos: function(todos) {
    return todos.length
  },
  _filteredTodos: function(todos, filter) {
    switch (filter) {
      case 'complete':
        return todos.filter(item => item.complete)
      default:
        return todos
    }
  }
})
```

So let's flesh this out with selectors:
```javascript
import { createSelector } from 'reselect'

const getTodos = state => state.todos
const getFilter = state => state.filterType

const totalSelector = createSelector(getTodos, items => items.length)

const filteredSelector = createSelector(getTodos, getFilter, (items, filter) => {
  switch (filter) {
    case 'complete':
      return items.filter(item => item.complete)
  }
})

Polymer({
  behaviors: [ ReduxBehavior ],
  // embed selectors to element
  selectors: {
    filter: filteredSelector
  },
  properties: {
    // using selector function
    total: {
      type: Number,
      stateSelector: totalSelector
    },
    // using embedded selectors
    todos: {
      type: Array,
      stateSelector: 'filter'
    },
  }
})
```

So they both achieve the same results, but reselect allows us to return properties based on other state values that the element may not be aware of, i.e. `filterType`. We don't need extra properties and our element looks cleaner. Also we can pull the selectors out into another file making the code more modular.

Thoughts, should this be a feature?

**Comment by tur-nr** [comment]
I've played with selectors (reselect) today and @cvanleeuwen is correct, just use the selector function as the `statePath`. Works a charm 😉  see pull request #18 to see the demo. Just use `polymer serve` to run it.

**Comment by ronnyroeller** [comment]
This looks very good. Thanks, guys!

One further idea: I don't want the selectors know how the related reducers are composed. Could we move this knowledge from the selector to the Polymer element?

For example based on your demo #18 : Imagine the reducer is sub reducers (called it `users`) of the state:
```
const users = (state, action) => {
  if (!state) return {
    friends: [],
    bffs: false
  }
  ...
const reducer = Redux.combineReducers({ users });
const store = Redux.createStore(reducer);
...
```

Currently, the selector would have to know about the composition:
```
const getBffs = state => state.users.bffs
const getFriends = state => state.users.friends
const friendsSelector = Reselect.createSelector(
  getBffs, getFriends, (bffs, friends) => {
```

How about instead localizing this knowledge in the Polymer element:

```
Polymer({
  is: 'friends-list',
  behaviors: [ ReduxBehavior ],
  properties: {
    friends: {
      type: Array,
      statePath: friendsSelector('users')
    }
  },
```

**Comment by tur-nr** [comment]
polymer-redux has no influence on how you create stores, reducers, selectors or elements. It only provides bindings. If you wish to have selector localisation within the element, feel free to do so. However I believe this isn't a concern for the polymer-redux.

Thanks again for the articles :smiley:
