### ISSUE TITLE
Why use new PolymerRedux(store)?

### ISSUE THREAD

**Issue by kritollm** [tur-nr/polymer-redux#19]
The function only return an object, so I don't understand the use of new. Please explain.

**Comment by tur-nr** [comment]
Tbh, I have no idea why. It's six and two threes to what way you create your behaviours.

This will change in the es2015 branch I'm working on to be a simple function call.

**Comment by kritollm** [comment]
The test passes without 'new' and from the docs a behaviours is just an object literal. https://www.polymer-project.org/1.0/docs/devguide/behaviors

Can probably skip the 'new', I did some testing and the constructor of `new PolymerRedux(store)` is the same as without new (`Object() { [native code] })`.

**Comment by tur-nr** [comment]
Yeah we could probably update the readme to remove the `new` keyword. Also, reading through the code, we require Redux library but never actually use it. Only the store instance, so we can clean that up too :smile:

**Comment by kritollm** [comment]
That sounds good. Polymer Redux solves a lot of problems, like data binding in a dynamically inserted polymer element. https://github.com/Polymer/polymer/issues/2477.

And of course better control of the data flow, it's very powerful.

It solved all the problems I thought I was going to get with Polymer.
