### ISSUE TITLE
Create Github release

### ISSUE THREAD

**Issue by ronnyroeller** [tur-nr/polymer-redux#24]
Could you please create a release (to have a fixed version that could be referred from a build using the polymer-redux)?

**Comment by tur-nr** [comment]
Unfortunately @jdomzhang had claimed the bower/npm package names with a fork of my repo. I was waiting until issue #2 is resolved. I will start to make releases from now and hopefully he will release bower/npm.

**Comment by ronnyroeller** [comment]
Fair point. I think it would be still beneficial if you could create a release. Users can always reference your package directly in the dependencies, e.g.:

```
polymer-redux": "tur-nr/polymer-redux",
```

**Comment by tur-nr** [comment]
bower/npm/github releases available
