### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by tur-nr** [tur-nr/polymer-redux#3]

**Comment by matejc** [comment]
+1
and an example would be nice too.

**Comment by tur-nr** [comment]
I'm working on a different approach for this, I have got the concept working just need to polish the repo and do some tests.

Check out https://github.com/tur-nr/polymer-redux/tree/diff-approach

**Comment by tur-nr** [comment]
Closing, see b8e9ed4cabd31ab4024e4936c5e09783bfc5d292
