### ISSUE TITLE
How to persist the store? [ES6]

### ISSUE THREAD

**Issue by kpgarrod** [tur-nr/polymer-redux#31]
I am experimenting with polymer-redux and would like to be able to persist the store to localforage. I came across the redux-persist library but it seems to use ES6 modules and I haven't been able to figure out how to add it to polymer-redux. Any suggestions please?

**Comment by tur-nr** [comment]
This has been a task I wanted to with `polymer-redux`, rewrite to ES6. I too was a little lost where to start as `Polymer` requires components via `<link>` tags. I believe the best approach is to follow this blog article: https://www.polymer-project.org/1.0/blog/es6.

To summarise the article you use a few tools [Vulcanize](https://github.com/Polymer/vulcanize), [Crisper](https://www.npmjs.com/package/crisper) and [BabelJS](https://babeljs.io/). First bundle using `Vulcanize`, then extract the bundled code with `Crisper` and finally `Babel` the extracted code.

If you wish to use ES6 modules syntax;

```js
import PolymerRedux from 'polymer-redux';
```

Then you are going to need another bundle process like Browserify or Webpack as Vulcanize can't do this Polymer/vulcanize#139. Using the respectful plugin/loader [polymerize](https://www.npmjs.com/package/polymerize), [polymer-loader](https://www.npmjs.com/package/polymer-loader).

Let me know how you go with this, as I will hopefully turn `polymer-redux` into an ES6 module eventually.

**Comment by tur-nr** [comment]
no further action required
