### ISSUE TITLE
using this lib with CQRS & Event Sourcing patterns ?

### ISSUE THREAD

**Issue by joeblew99** [tur-nr/polymer-redux#38]
with a unidirectional data flow, it starts to make it much easier to use a CQRS pattern.

Here is a decent link that talks about this pattern:
https://medium.com/technology-learning/event-sourcing-and-cqrs-a-look-at-kafka-e0c1b90d17d8#.tz1prk37t.

The core idea is to store the event and its data. YOu can then replay the event back whenever you want to mutate the state.

This allows a store and forward style pattern. It can even happen between Polymer components IF you wanted OR between a Server and a Polymer web app.

I am new to Polymer and Redux on the client but have done a fair bit of CQRS on the server.
So i was wondering if there are any thought about this for this library ?

Sorry about such an open ended discussion here. I am more than happy to take it elsewhere if you want. But i feel that this library is very important to the success of  enterprise Polymer projects and wanted to raise it.

**Comment by timeu** [comment]
Replaying events and time-travel debugging are both supported by `Redux` and also work fine if you are using `polymer-redux`. Check out the [redux-devtools](https://github.com/gaearon/redux-devtools) which supports all of that. 
For dealing with side effects (Ajax calls to the backend, IO, etc) you need to either use [redux-thunk](https://github.com/gaearon/redux-thunk) or [redux-saga](https://github.com/yelouafi/redux-saga) (I would recommend `redux-saga´). Check out this [issue](https://github.com/tur-nr/polymer-redux/issues/13)

**Comment by joeblew99** [comment]
@timeu awesome !!! backend linkage is exactly why i brought up CQRS. You read my mind

on the backend i use golang.

I wil read up on the two links - thankyou

**Comment by tur-nr** [comment]
The library focuses on just the bindings alone. It doesn't enforce concepts
or opinions. Like @timeu suggested, look at how others are using redux to
make server calls/sync with your data store.

The beauty of polymer-redux is that it doesn't force your store to be aware
of polymer. So you write your reducers however you wish, following redux
patterns and practices. Then just link it up with your components and it
"just works", famous last words :P
