### ISSUE TITLE
Consume Redux as AMD module

### ISSUE THREAD

**Issue by nazar-pc** [tur-nr/polymer-redux#40]
Since both this project and Redux declare themselves as AMD modules, why not consume Redux as AMD module and require it to be manually added to the page?
Should be pretty easy to do.

**Comment by nazar-pc** [comment]
I've just looked through the source code and this project doesn't directly use Redux itself.
Maybe clarify docs a bit that Redux can be consumed in any way and is not called directly from polymer-redux?

**Comment by tur-nr** [comment]
Redux as a dependency was from earlier drafts of the library. The docs were confusing, I've removed the comments about the boilerplate.

Thanks :smile_cat:
