### ISSUE TITLE
Question: How to give Elements access to ReduxBehavior?

### ISSUE THREAD

**Issue by nwaywood** [tur-nr/polymer-redux#42]
In the [example](https://github.com/tur-nr/polymer-redux/blob/master/demo/index.html) the `friends-list` element is defined within the same scope of `ReduxBehavior` so it has direct access to the variable. i.e.

```
behaviors: [ ReduxBehavior ]
```

I'm struggling to figure out how to give elements access to `ReduxBehavior` in a 'real world' scenario where elements are defined in separate files. 

I have tried:

- setting `ReduxBehavior` to the global `window` object 
- using [iron-meta](https://elements.polymer-project.org/elements/iron-meta)

but neither seemed to work.

What is the correct way to define the redux `store` and `ReduxBehavior` in a global location and make `ReduxBehavior` available to child elements defined in their own files?

**Comment by kristfal** [comment]
@nwaywood I'd recommend using it the way you create/scope behaviors. When creating a behavior from scratch, be it a `Polymer` branded behavior, or an app name spaced behavior, eg `myApp`, you're actually putting this behavior in the global window scope.

Let's say you have a file called `reducers.js` which contains your reducers and code for initializing the store. Your app is called `myApp` and you'd like to import the reduxBehavior to an element called `my-element`. We'll also assume that you have redux available in the global window scope. An alternative is to import it in your `reducers.js` file.

The `reducers.js` file could look something like this:

```js

let myApp = myApp || {}

// Don't pollute the global namespace
(function () {

  const defaultAppState = {
    foo: 'bar'
  }
  
  function app(state = defaultAppState, action) {
    switch(action.type) {
       // Reducer logic here
    }
  }
 
 // Create more reducers or import other reducers here
 

 // Combine reducers if you have multiple
 myApp.AppReducer = window.Redux.combineReducers({
   app,
   otherReducer
});

 // Create the redux store and apply middleware if you need it
 myApp.ReduxStore = window.Redux.createStore(myApp.AppReducer, window.Redux.applyMiddleware(window.ReduxThunk.default);

 // This is where we create the polymer redux behavior on the redux store
 myApp.ReduxBehavior = window.PolymerRedux(myApp.ReduxStore);

})();
```

Import `reducers.js` file in your `index.html`

In your polymer element, you can now import this behavior like this:

```html


<script>
  (function() {
  'use strict';
    new Polymer({
      is: 'my-element',
      behaviors: [
        myApp.ReduxBehavior
      ],
      properties: {
        
         app: {
           type: Object,
           statePath: 'app',
           observer: '_onAppChange'
         }
       },

        _onAppChange: function(change) {
            // Do your thing here
       }
   })()
     

```

There are probably other ways of doing this, but this should at least get you started.

**Comment by nwaywood** [comment]
@kristfal Thank you for the detailed response, I got it working 😃

**Comment by tur-nr** [comment]
@kristfal, I think we should open a wiki or starter project. You're setup is good, thanks for sharing.

**Comment by kristfal** [comment]
@tur-nr Thanks, I think that is a good idea. I'm personally more a fan of a Wiki than starter projects, as more often than not, I've already started with a 'polymer starter project' of some kind (either the official PSK or a flavored alternative). Would be happy to contribute in any way, just let me know what you want. Also, feel free to use what I added as a beginning.

Regarding best practices and working with larger projects (which is the point of using polymer-redux imo), I have some questions/thoughts that would be great to get your input on.

I'm contemplating about how to split the `reducers.js` into multiple files in a 'polymer' fashion without using require, webpack or any other non-polymer tooling. Got any ideas?

Currently leaning towards using HTML imports and composition through polymer behaviors, building a `polymer-redux` element which imports dependencies and a bunch of behaviors where each behavior defines a reducer. The `polymer-redux` element would then expose a consolidated `reduxBehavior` with the combined reducers to the global scope.

Can you think of any other alternatives to this approach which follows the 'polymer' way?
