### ISSUE TITLE
Dispatching actions via the actions property not working

### ISSUE THREAD

**Issue by nwaywood** [tur-nr/polymer-redux#43]
I have a simple polymer element that I am dispatching an action from. It works when supplying the action object directly in the dispatch call:

```
Polymer({
  is: 'emma-app',
  behaviors: [ myApp.ReduxBehavior ],
  created: function() {
      // this works!
      return this.dispatch({type: 'INCREMENT'})
  }
});
```

but when I try to do the same thing using the `actions` property it doesn't work:

```
Polymer({
  is: 'emma-app',
  behaviors: [ myApp.ReduxBehavior ],
  actions: {
      increment: function() {
          return {
              type: 'INCREMENT'
          };
      }

  },
  created: function() {
      // this doesn't work
      return this.dispatch('increment')
  }
});
```

I got the following error in the browser

`index.js:316 Uncaught Error: Actions must be plain objects. Use custom middleware for async actions`

However if I understand correctly the two examples above should be the same and thus should not require any async middleware.

**Comment by kristfal** [comment]
The polymer `created` callback is fired before property values are loaded, and redux actions are loaded along those property values on the `attached` and `ready` callbacks.

Try dispatching in the `ready` callback instead. You might need to defer the action one microtick (wrap it in an `async` method) for it to fire properly.

**Comment by tur-nr** [comment]
This is an issue with the documentation.

@kristfal is correct, the lifecycle event you want is `ready`. For some reason the documentation informs developers it happens on `created`.
