### ISSUE TITLE
Question about state

### ISSUE THREAD

**Issue by smatthews1999** [tur-nr/polymer-redux#46]
So far your component is working great for me.  I had one question...
Regarding your demo app...
https://github.com/tur-nr/polymer-redux/blob/master/demo/index.html#L47
Doesn't this line overwrite the state?
```
 state.friends = friends;
```
... while I'm quite sure it doesn't, I was hoping you could explain it.
Thanks.

**Comment by tur-nr** [comment]
I think the examples are just to demonstrate how the bindings work. This maybe just how I wrote the reducer. You could do the following, and it would make no difference.

```javascript
const reducer = (state, action) => {
    // logic...
    return {
        friends
    };
};
```

How you write your reducer is up to you, PolymerRedux behaviours don't really care. So I wouldn't focus to much on the reducers in the examples.

_FYI_ if you are using large lists and Polymer 1.0 you may want to read https://medium.com/collaborne-engineering/stop-polymer-lists-from-flickering-b2736d56a2e1 You can read more on this issue #13.

**Comment by smatthews1999** [comment]
Ok Thanks.
