### ISSUE TITLE
Binding on "ready" state maybe too late in event cycle.

### ISSUE THREAD

**Issue by smatthews1999** [tur-nr/polymer-redux#47]
Hey..
I was wondering if I could ask what may be the issue here...
I am using your redux component with some input controls, such as paper-input and vaadin-combobox.  In the latter case there seems to be an initialization issue.  I have gone through the code but I can't figure it out.  The error I'm getting is as follows...
![image](https://cloud.githubusercontent.com/assets/562964/21959589/bb0c15b2-da99-11e6-9855-c55f6f2b3a49.png)

The error only happens on initialization of the form, and does not occur once the form is loaded.  It also does not seem to prevent it from working.  

I have followed the code up to the error and it looks as if it is rejecting my 'action' because it is a string and not an object.  The string is only the name of the action : 'setRecipe' in this case.

Each input is configured the same way ...
```
<paper-input label="Cook Time" auto-validate pattern="[0-9]*" value="{{recipe.time}}" error-message="Numbers Only Please!"
      on-change="onRecipChange"></paper-input>

    <vaadin-combo-box label="Hours/Min" items="[[timeMeasures]]" value="{{recipe.timeMeasure}}" on-change="onRecipChange"></vaadin-combo-box>

    <paper-input label="Tempurature (F)" auto-validate pattern="[0-9]*" value="{{recipe.temp}}" error-message="Numbers Only Please!"
      on-change="onRecipChange"></paper-input>

    <paper-input label="Serves" auto-validate pattern="[0-9]*" value="{{recipe.serves}}" error-message="Numbers Only Please!"
      on-change="onRecipChange"></paper-input>
```
the 'onRecipeChange' is basically dispatching the state of the data entry.
```
 onRecipChange: function (ev) {      
      this.dispatch('setRecipe', this.recipe);
 }
```
Thanks for the great component!
Sam

**Comment by tur-nr** [comment]
Could you possibly give me a link to a working example? It's hard to know without seeing how the components are setup. Thanks.

**Comment by smatthews1999** [comment]
Here is a [CodePen](http://codepen.io/smatthews1999/pen/OWRmqB) that I beleive has all the versions I am using.  The error comes out in the console.  Otherwise it all seems to be working.
Thanks.

**Comment by tur-nr** [comment]
The issue lays with the lifecycle of components. So here's the event sequence;

1. `<my-test>` `created`
2. `<vaadin-combo-box>` `created`
3. `<vaadin-combo-box>` `ready`
4. `<my-test>` `ready`

`PolymerRedux` components applies bindings on `ready` events. The problem is that `<vaadin-combo-box>` initialises an empty value, `this.value = '';`, on `ready`. This triggers an `on-change` in `<my-test>` that dispatches an action. **But**, we know from the lifecycle above that the component has no bindings to redux yet.

This is an issue as you want the top-level application element to host the bindings and then push data down. Which means you will always encounter this with elements that initialise values on `ready` events. The bindings initialisation may have to go into `created` event.

**Comment by smatthews1999** [comment]
Awesome!  Thanks for the explanation.  Here is the fixed [CodePen](http://codepen.io/smatthews1999/pen/OWRmqB)

**Comment by tur-nr** [comment]
This seems a little hacky. Gonna reopen and until we get a cleaner approach.

**Comment by smatthews1999** [comment]
I'm sure it's not a trivial matter but it would be great if the state could be available prior to "ready".  I am encountering a few places where it has become an issue.  I am finding that properties with observers are being called prior to "ready".  Alternatively I wonder if it would be possible to query the polymer-redux state for it's readyness prior to calling "dispatch" on it?
TIA.

**Comment by tur-nr** [comment]
We can't use `created` event as Polymer hasn't set the property values yet.

**Comment by Phenome** [comment]
Just subbing as I'm having the same problem with polymerfire. I'll try to work around it, but it'd be great if perhaps the dispatch calls could wait and fire only after the bindings to redux are there.

**Comment by Phenome** [comment]
Would something like this work? It does work. Not sure if it's too hacky, if it could lead to other problems, and wasn't sure if it's clean enough, so I didn't try a PR. Good for discussion, I hope.

https://www.diffchecker.com/WvRI6g1g

**Comment by tur-nr** [comment]
Turns out a little simpler than I thought. Just make sure the action creators are compiled on `created`.
