### ISSUE TITLE
Doesn't work in Microsoft Internet explorer 11

### ISSUE THREAD

**Issue by javamaniac** [tur-nr/polymer-redux#48]
Object.assign is not supported in Microsoft Internet explorer 11.

It works fine with the Polyfill : https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by tur-nr** [comment]
I haven't got the setup for IE. Could you please check `object-assign` branch and test. Thanks 😄
