### ISSUE TITLE
actions documentation

### ISSUE THREAD

**Issue by tomberek** [tur-nr/polymer-redux#53]
It seems that instead of `actions` does not work, but using `_reduxActions` will work. See below.

Is this expected or documented? Related to the Polymer 2.0 change?

```
Polymer({
    _reduxActions: {
        setName: function(first, last) {
            return {
                type: 'SET_NAME',
                first: first,
                last: last
            };
        }
    },
    handleClick: function() {
        return this.dispatch('setName', 'James', 'Bond');
    }
});
```

**Comment by tur-nr** [comment]
No, don't use that, the underscore signals private. Things are private for a reason. Can you share your code that doesn't work so I can get a close look.

**Comment by tomberek** [comment]
It seems it works when redux-thunk is used, but before that it complains that the action is not a plain javascript object (it's a string at that point, has not been converted).

**Comment by tur-nr** [comment]
Is this related to #47?

**Comment by tomberek** [comment]
yes, looks identical
