### ISSUE TITLE
Redux state lost on page route change

### ISSUE THREAD

**Issue by camerow** [tur-nr/polymer-redux#61]
I'm using https://erikringsmuth.github.io/app-router/ with polymer-redux and when I change routes my whole redux state is reinitialized. 

Do you have any thoughts or experience on this issue? 

I'm experienced with React/Redux, but am *very* new to the Polymer library and way of doing things. I would provide more information but at the moment I'm still in the process of understanding what is actually going wrong.

**Comment by timeu** [comment]
Can you post some code ? 
I guess you store the current route in your redux store. How do you update it ?

**Comment by camerow** [comment]
The routing is all handled by app-router like so:
`my-app.html`:

```
<link rel="import" href="redux-store.html">

...
<er-default-app-layout>
      <app-router mode="pushstate">
          <app-route path="/list" element="list-view"></app-route>
          <app-route path="*" element="my-view404"></app-route>
      </app-router>
    </er-default-app-layout>
```

Following a link to those routes resets the redux state. It seems like my `redux-store.html` is not acting as a singleton, but being called on each route load:

`redux-store.html`

```
<script src="incidents/reducer1.js"></script>
<script src="patients/reducer2.js"></script>
<script src="appReducer.js"></script>

<script>
    var rootReducer = Redux.combineReducers({
        one: reducer1,
        two: reducer2,
        appState: appReducer,
    });

    var store = Redux.createStore(
        rootReducer,
        window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
    );
    /**
    * Behavior that implements a Redux Store for er-field-pcr.
    *
    */
    /** @polymerBehavior ReduxBehavior */
    ReduxBehavior = PolymerRedux(store);     // eslint-disable-line
</script>
```

**Comment by tur-nr** [comment]
Can you add `console.count('store-init');` to the `redux-store.html` and see how many times it is imported.

**Comment by camerow** [comment]
It's only `1` but it's `1` each time I route to a new view.

**Comment by camerow** [comment]
`store-init 1` -> click a new route -> redux set to `initialState` -> `store-init 1`, rinse and repeat.

**Comment by timeu** [comment]
Can you try to move the store and reducer definitions out of the `redux-store.html` into the index.html. 

The `redux-store.html` should only contain the `ReduxBehavior = PolymerRedux(store);` call.

**Comment by tur-nr** [comment]
https://drive.google.com/file/d/0B9Kng2xJYUFnTllJWEhEaWxaLVk/view?usp=sharing

Seems to be working for me? Keeps the state after changing routes.

**Comment by gabema** [comment]
Appreciate the discussion and help troubleshooting but we solved the problem. It was related to how we were triggering navigations using https://github.com/erikringsmuth/app-router.

**Comment by camerow** [comment]
Thanks for the help, this is safe to close!
