### ISSUE TITLE
polymer lint and polymer-build fail due to ReduxBehavior not registering properly

### ISSUE THREAD

**Issue by gabema** [tur-nr/polymer-redux#62]
polymer-redux is working great so far in the new Polymer based app we are developing.  We just have two problems.

First problem is when trying to run ```polymer lint``` I see one of the following warnings for each custom element that includes the ReduxBehavior.

> Behavior ReduxBehavior not found when mixing properties into my-app!

All attempts to remedy this problem using a comment like follows failed.
```/** @polymerBehavior ReduxBehavior */```

Second larger problem manifested when trying to build the project using gulp with a stock gulpfile.js generated via polymer-build and generator-polymer-init-custom-build and polymer-cli.

Running gulp build results in the following error:
> error:   In src/my-view1.html: [unknown-polymer-behavior] - Unable to resolve behavior `ReduxBehavior`. Did you import it? Is it annotated with @polymerBehavior?

polymer-redux is working as expected using `polymer build` and `polymer serve`

**Comment by basvanbeek** [comment]
Same issue here with the added bonus of polymer build now failing too.

Quick hack to make polymer build work:

`const ReduxBehavior = Object.assign({}, PolymerRedux(store));`

**Comment by tur-nr** [comment]
The name of the polymerBehavior needs changing is, I will make an update.

Does anyone else getting the following when they run `polymer build` 

![Imgur](http://i.imgur.com/YYTmtS5.png)

**Comment by tur-nr** [comment]
Use v0.4.1 for updates.

**Comment by tpluscode** [comment]
I'm having this issue with 0.4.2 and polymer-cli 0.18. Can't `lint` or `build`. Whatever I do I get either `unknown-polymer-behavior` or `could-not-determine-behavior-name`. I tried the `Object.assign()` trick to no avail. 

Here's a repro attached: [redux.zip](https://github.com/tur-nr/polymer-redux/files/937772/redux.zip)

**Comment by tpluscode** [comment]
see Polymer/polymer-analyzer#632
