### ISSUE TITLE
polymer2 branch - how to know the redux initialization for an element is complete?

### ISSUE THREAD

**Issue by phani1kumar** [tur-nr/polymer-redux#67]
How can I know Redux is initialized for a custom element? I've a wiered problem. 

I've a ES6 custom element, in which firing a `dispatch` event before the ReduxMixin is completely initialized, I am getting error stating that the given element doesn't have any actions, and the class loading / initializing is failing permanently . Is there a way to know if Redux is initialized properly for a given element?  Loading is abandoned after the properties are bound at `bind(this,properties)` Following is the snippet from polymer-redux.html::
```     return function (parent) {
        return class ReduxMixin extends parent {
            connectedCallback() {
                var properties = collect(this.constructor, 'properties');
                bind(this, properties);

                var actions = collect(this.constructor, 'actions');
                Object.defineProperty(this, '_reduxActions', {
                    configurable: true,
                    value: actions
                });

                // ^^^ bind first, fixes #66
                super.connectedCallback();
            }

            disconnectedCallback() {
                unbind(this);
                super.disconnectedCallback();
            }```

I want to defer the dispatch until the Redux is completely initialized for the element.

**Comment by tur-nr** [comment]
Hey man, can you pull the latest from the `polymer-2` branch. Hopefully the actions should be available first before properties are initialised and observers are triggered.

**Comment by phani1kumar** [comment]
Thank you very much for the quick fix @tur-nr Now the issue is gone and the loading works smoothly. Thank you once again for the quick fix.
