### ISSUE TITLE
use of multiple redux behaviors on same component

### ISSUE THREAD

**Issue by christophe-g** [tur-nr/polymer-redux#68]
Hey, 

First of all, thanks a lot for this library - very usefull.

Before I get into coding and propose a PR, I'd like to have some feedback on best way to handle a case where you would have two (or more) redux behaviors defined for the same element. 

Instead of using [combineReducers](http://redux.js.org/docs/api/combineReducers.html) and for reducers handling specific business-logic, I would prefer keeping them separated - each one as a redux behavior. Something along those lines: 

## PolymerRedux
```js 
  const initialGlobal = {
    language: 'en'
  };
  
  const reducer = (state, action) => {
    if (!state) {
      return initialGlobal;
    }

    switch (action.type) {
      case 'SET_LANGUAGE':
        return Object.assign({}, state, {
          language: action.language
        });
    }
  };
  
  const initialSub = {
    user: 'Alphonse'
  };

  const reducerSub = (state, action) => {
    if (!state) {
      return initialSub;
    }

    switch (action.type) {
      case 'SET_USER':
        return Object.assign({}, state, {
          user: action.user
        });
    }
  };

  const storeGlobal = Redux.createStore(reducer);
  const storeSub = Redux.createStore(reducerSub);

  state = PolymerRedux(store);
  stateSub = PolymerRedux(storeSub);
```
## Element
```js
 Polymer({
    is: 'redux-test',

    behaviors: [
      stateSub,
      state
    ],

    properties: {
      user: {
        type: String,
        statePath: 'user'
      },
      language: {
        type: String,
        statePath: 'language'
      }
    },

    setLanguage: function(e, d) {
      this.dispatch({
        type: 'SET_LANGUAGE',
        language: 'ru'
      });
    },

    setUser: function(e, d) {
      stateSub.dispatch.call(this,{
        type: 'SET_USER',
        user: 'christophe'
      });
    }
  });
```
For the time being it does not work. 

This approach makes sense to me, as it does allows to keep state management in separate behaviors/files, is easy to compose, and avoids deep nested statePath. 

Is there already a kind of best practice that would be recommended to tackle this case ?
If not, we shall have a couple of minor modification in the code base, mainly : 
- allow each behavior to set its own `statePath` property, so that we would only register listeners to the adequate element properties. We would then allow construct a reduxBehavior with its `statePath` property name   `stateSub = PolymerRedux(storeSub, 'subStatePath');`
- make sure we can properly unsubscribe each storeListeners.

Ideas/feedback welcome, especially if this is a bad idea  - it would prevent submitting a PR for nothing.
Thanks

**Comment by tur-nr** [comment]
Generally when using Redux you would only have one store. I'm against the idea of Elements having multiple stores. It will introduce too many problems and complexities for the bindings like store management and property duplicates.

What I will suggest is do some research about why you are choosing Redux. The author himself wrote an article on [why you may not need Redux](https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367). It is written using React but you can apply Polymer to re-evaluate your use case.

If Redux is the choice for your app, then I would seriously think about using the tools and utilities that have come from or been adopted by it's community, [Redux Ecosystem](http://redux.js.org/docs/introduction/Ecosystem.html).

These are the most common ones I use and I haven't had any desire for multiple stores, even with a very large data set:

- [`.combineReducers()`](http://redux.js.org/docs/api/combineReducers.html)
- [reselect](https://github.com/reactjs/reselect)
- [normalizr](https://github.com/paularmstrong/normalizr)

PR's are always welcome 👍

**Comment by christophe-g** [comment]
Thanks a lot for this detailed answer!

I thought I came across a blog post stating using multiple behaviors (one for each store) felt like the polymer way to handle this situation. Could not find back the source.

Anyway, I did some reshape of my state data and am happily using combineReducers to now only have one store. 

C.
