### ISSUE TITLE
Question: Is there a way to access the state outside of the reducer or a propertyBinding?

### ISSUE THREAD

**Issue by Mika83AC** [tur-nr/polymer-redux#69]
Hello,

first thx for the work on PolymerRedux!

Started using it yesterday, my biggest "issue" until now is that I'm not able to access the state itself outside of the reducer or a property binding (via statePath in an polymer element).

Is there any way to accomplish this? As I've many functions outside of the reducer relying on access to the apps state, I'm stuck here without direct (read only) access to it. Do I have to "mirror" every property of the state as a property binding in the element I need access to it (which creates much overhead)?

Regards,
Michael

**Comment by tur-nr** [comment]
Use the `.getState()` method on your Elements, or listen for the `state-changed` event. I would use the event as if will be more _reactive_.

_Polymer v1.x_
```js
Polymer({
    is: 'my-element',
    behaviors: [ ReduxBehavior ],

    // via event
    ready: function() {
        this.on('state-changed', function(state) {
            // do something with state
        });
    },

    // via method
    doSomething: function() {
        var state = this.getState();
        // do something with state
    }
});
```

_Polymer v2.0_
```js
class MyElement extends ReduxMixin(Polymer.Element) {
    // via event
    constructor() {
        super();
        this.addEventListener('state-changed', (event) => {
            const state = event.detail;
            // do something with state
        });
    }

    // via method
    doSomething() {
        const state = this.getState();
        // do something with state
    }
}
```

**Comment by Mika83AC** [comment]
Thank you master Turner, that is exactly what I was looking for!

Regards,
the Padawan who's not reading the documentation close enough ... sorry :)
