### ISSUE TITLE
Error using minified code outside of NODE_ENV === 'production'

### ISSUE THREAD

**Issue by rkief** [tur-nr/polymer-redux#71]
I am using polymer CLI in Visual Studio Code on Windows 10 to build the application,  (polymer build)  When I serve the application using polymer serve build/unbundled -o, there is the following error in the console:

You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

I have tried many methods to set the environment variable,  Here is the polymer.json:

[polymer.txt](https://github.com/tur-nr/polymer-redux/files/914688/polymer.txt)

Any thoughts on setting the environment variable or modifying the polymer.json file?

**Comment by rkief** [comment]
Using the polymer-2 branch.

**Comment by tur-nr** [comment]
Have you tried looking at the compiled code (unminified) and see what loose-envify is setting for `process.env.NODE_ENV`?

**Comment by vilarfg** [comment]
@rkief have you tried:
```
set NODE_ENV=production
```
for windows or
```
export NODE_ENV=production
```
for linux and mac ?

**Comment by shawnd** [comment]
I'm having the same error with my build.

`{
    "addServiceWorker": true,
    "bundle": false,
    "js": {"minify": true, "compile": true},
    "html": {"minify": true},
    "css": {"minify": true}
  }]`

**Comment by TrebuhD** [comment]
I'm getting this error too. This issue should probably be reopened.

**Comment by mccabep67** [comment]
ditto - can't find a solution to this.

**Comment by tur-nr** [comment]
I don't agree that this is an issue. This is a build process not using Redux's minified version. I'm failing to see how this is an issue of `polymer-redux`.

Surely this should be taken up with the Polymer team in the [bundler](https://github.com/Polymer/polymer-bundler) repo?

**Comment by mccabep67** [comment]
Ok thanks tur-nr appreciate the response.

**Comment by tur-nr** [comment]
If you create an issue, please link back to this issue so I can track it. Thanks :)
