### ISSUE TITLE
Use of combineReducers with polymerRedux

### ISSUE THREAD

**Issue by pedrule** [tur-nr/polymer-redux#72]
Hi,  it seems that the reducers states don't bind with polymer elements when the store is constructed with a combinedReducers. Is anyone have encountered this problem before ?

**Comment by tur-nr** [comment]
Check what the value of the store's state is and see if it matches your `statePath`.

**Comment by tpluscode** [comment]
In other words, when you combine these two

```
const a = (state, action) => {
  return { stateA: "foo" };
};

const b = (state, action) => {
  return { stateB: "bar" };
};

var combined = combineReducers({
  reducerA: a,
  reducerB: b
});
```

then you need to prefix the `statePath` accordingly:

```
properties: {
  stateOfA: {
    statePath: 'reducerA.stateA'
  },
  stateOfB: {
    statePath: 'reducerB.stateB'
  }
}
```

**Comment by pedrule** [comment]
great answer, thanks for time spent to explain.

Pierre


*Pierre Alibert*


*Visites virtuelles Google, kézako ?
<https://www.youtube.com/watch?v=zJH89F7nOmo>*



+33 7 77 03 80 92

2017-04-20 3:40 GMT+02:00 Christopher Turner <notifications@github.com>:
