### ISSUE TITLE
Trouble running polymer-redux 2 demo

### ISSUE THREAD

**Issue by JoeCodeswell** [tur-nr/polymer-redux#78]
Hi Christopher,

I am pretty new to both polymer & redux. I am trying to get the polymer-redux 2 demo running.
In trying to follow the README.md, I have:

unziped https://github.com/tur-nr/polymer-redux/tree/polymer-2   TO .../UsePRdx_Pcast61Pj/polymer-redux-polymer-2

    $ cd .../UsePRdx_Pcast61Pj/polymer-redux-polymer-2
    $ bower install --save polymer-redux#polymer-2
    $ cd demo
    $ polymer serve
    info:    Files in this directory are available under the following URLs
          applications: http://127.0.0.1:8081
         reusable components: http://127.0.0.1:8081/components/demo/

Browsing in chrome to http://127.0.0.1:8081/ **yields a blank screen**.

I notice that demo/index.html references  `../../webcomponentsjs/webcomponents-lite.js`

The above steps did not produce this reference for me. What am I missing?

Thanks for the help.

Love and peace,

Joe

**Comment by tur-nr** [comment]
You should go to: http://localhost:8081/components/polymer-redux/demo/index.html

The landing page for polymer-2 branch isn't complete due to some components from PolymerElements being a little unstable during development. I will revise this again once these components are stable with Polymer 2.

**Comment by JoeCodeswell** [comment]
Hi Christopher,

Thanks for the response.
I just tried your suggestion. The page is still blank.
Love and peace,
Joe

**Comment by tur-nr** [comment]
There are no warnings in your terminal? Also Chrome's console?

I've tried a fresh checkout (`npm install && bower install`), `polymer serve`. Everything works accordingly.
