### ISSUE TITLE
Merge polymer-2 into master

### ISSUE THREAD

**Issue by tur-nr** [tur-nr/polymer-redux#79]
- [x] Create `develop/v0` branch for Polymer v1.x
- [x] Merge `polymer-2` branch into `master`
- [x] Release new major version

**Comment by abdonrd** [comment]
How is the status of this?

Thanks in advance! 👏

**Comment by tur-nr** [comment]
Trying to resolve some breaking changes when updating dependencies and a few housekeeping stuff left to do. Hopefully not too long :)

**Comment by ronnyroeller** [comment]
@tur-nr Is there anything we can help with upgrading polymer-redux to Polymer 2?

**Comment by tur-nr** [comment]
@ronnyroeller thanks for offering your help.

So here are the two failures I'm getting, maybe you could help.

_Polymer Lint_
`polymer lint` is returning warning which won't pass the tests

```
index.js(149,34) warning [unknown-superclass] - Unable to resolve superclass parent
```

Documenting the block of code with `@polymerMixin` or `@polymerMixinClass` does not prevail.

_Firefox Fails_

Firefox hangs in the tests. WCT opens firefox but seems like the tests are never loaded or run so the timeout hits failing them.

**Comment by tur-nr** [comment]
So I managed to fix the linting issue, turns out the `@polymerMixin` was placed on the wrong block of code so the analyzer wasn't picking it up.

Still no luck on the Firefox hang, but master is currently not testing Firefox through CI so I may go ahead with the merge.

**Comment by tur-nr** [comment]
[v1.0.0](https://github.com/tur-nr/polymer-redux/releases/tag/v1.0.0) released.
