### ISSUE TITLE
combineReducers doesnt trigger statePath

### ISSUE THREAD

**Issue by benzile** [tur-nr/polymer-redux#82]
Using combineReducers somehow breaks down the binding of the statePath.
As long as i m using one reducer then there is no problem but when I:

 const store = Redux.createStore(
            Redux.combineReducers({reducer:reducer}),
            Redux.applyMiddleware(ReduxThunk)

    );

i can see it reaches into the correct reducer and actually changing the state, moreover, the store.subscribe is triggered as well but the statePath binding in my Polymer is not firing anymore...

some code:

index.html:

<!DOCTYPE html>
<html lang="en">
<head>
    <script src="/bower_components/webcomponentsjs/webcomponents-lite.js"></script>
    <script src="/node_modules/redux/dist/redux.js"></script>
    <script src="/node_modules/redux-thunk/dist/redux-thunk.js"></script>

    <link rel="import" href="ip-canvas.html">
    <link rel="import" href="ip-engine.html">

    <style>

    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>Title</title>
</head>
<body>
<ip-canvas></ip-canvas>
<ip-engine></ip-engine>
</body>
</html>

The store:

`<script>
    trigger = 0;
    const intialState = {

        components:{
            canvas: {
                a:5
            },
            engine: {
                originator: '',
                command: '',
                deltaX: '',
                deltaY: '',
                trigger: true
            }
        }
    };

    const reducer = (state, action)=>{
        if(!state) return intialState;
        switch (action.type){
            case 'MOVE':
                trigger = trigger + 1;
                return { ...state,
                    components : {
                        ...state.components,
                        engine :{
                            originator: action.originator,
                            command: action.specific,
                            deltaX: action.deltaX,
                            deltaY: action.deltaY,
                            trigger: trigger
                        }
                }
        }
    }}

    let ReduxThunk = window.ReduxThunk.default;

    const store = Redux.createStore(
   //if change it to just reducer then everything works
            Redux.combineReducers({reducer:reducer}),
            Redux.applyMiddleware(ReduxThunk)

    );
    let render = ()=>{
        console.log('rendering');
    };
    store.subscribe(render);

    const ReduxBehavior = PolymerRedux(store);
    const AsyncActionsBehavior = {
        actions: {
            moveSequence: (command, originator, specific, deltaX, deltaY)=> {
                return (dispatch)=>{
                    dispatch({type: command, originator: originator, specific: specific,  deltaX: deltaX, deltaY: deltaY});
                }
            }
        }
    }`

the dispatching element:

<link rel="import" href="bower_components/polymer/polymer.html">
<link rel="import" href="redux-store.html">

<dom-module id="ip-canvas">
    <style>
        #mainCanvas {

            height : 100%;
            width: 100%;
            position: relative;
        }

        #mainContainer {
            height: 720px;
            width: 1280px;
            border: 1px black solid;

        }

    </style>
    <template>
        <div id="mainContainer">
            <canvas height="720px" width="1280px" id="mainCanvas" style="border:1px solid black"></canvas>
        </div>

    </template>
    <script>
        Polymer({
            is: "ip-canvas",
            behaviors: [ ReduxBehavior, AsyncActionsBehavior ],
            properties: {
                trigger: {
                    type: Boolean,
                    value: '',
                    statePath: 'components.engine.trigger'
                }

            },
            ready: function(){
                this.mouseStart = this._mouseStart.bind(this);
                this.mouseMove = this._mouseMove.bind(this);
                this.mouseEnd = this._mouseEnd.bind(this);
                this.touchStart = this._touchStart.bind(this);
                this.touchMove = this._touchMove.bind(this);
                this.touchEnd = this._touchEnd.bind(this);
                this.preventBub = this._PreventMouseBubbling.bind(this);
                this.$.mainCanvas.addEventListener('mousedown',this.mouseStart);
                this.$.mainCanvas.addEventListener('touchstart',this.touchStart);
                this.$.mainCanvas.addEventListener('contextmenu', this.preventBub);
                document.addEventListener('contextmenu', this.preventBub);
                this.$.mainContainer.addEventListener('contextmenu', this.preventBub);
            },

            _mouseStart: function(e){
                this._PreventMouseBubbling(e);
                this.$.mainCanvas.removeEventListener('mousedown',this.mouseStart);
                this.$.mainCanvas.removeEventListener('touchstart',this.touchStart);
                this.$.mainCanvas.addEventListener('mouseup',this.mouseEnd);
                this.$.mainCanvas.addEventListener('mousemove',this.mouseMove);
                this.dispatch('moveSequence','MOVE','canvas','tumbleStart', e.clientX, e.clientY);
            },

            _touchStart: function(e){
                this._PreventMouseBubbling(e);
                if(e.targetTouches.length == 1){
                    this.$.mainCanvas.removeEventListener('mousedown',this.mouseStart);
                    this.$.mainCanvas.addEventListener('touchmove',this.touchMove);
                    this.$.mainCanvas.addEventListener('touchend',this.touchEnd);
                    this.dispatch('moveSequence','MOVE','canvas','translateStart', e.targetTouches[0].clientX, e.targetTouches[0].clientY);
                } else if(e.targetTouches.length == 2){
                    this.$.mainCanvas.removeEventListener('touchstart',this.touchStart)
                    this.dispatch('moveSequence','MOVE','canvas','pinchStart', e.targetTouches[0].clientX, e.targetTouches[0].clientY);
                }
            },

            _mouseMove: function(e){
                this._PreventMouseBubbling(e);
                this.dispatch('moveSequence','MOVE','canvas','tumbleMove', e.clientX, e.clientY);
            },

            _touchMove: function(e){
                this._PreventMouseBubbling(e);
                if(e.targetTouches.length == 1){
                    this.dispatch('moveSequence','MOVE','canvas','translateUpdate', e.targetTouches[0].clientX, e.targetTouches[0].clientY);
                } else if(e.targetTouches.length == 2){
                    this.dispatch('moveSequence','MOVE','canvas','pinchUpdate', e.targetTouches[0].clientX, e.targetTouches[0].clientY);
                }
            },

            _mouseEnd: function(e){
                this._PreventMouseBubbling(e);
                this.$.mainCanvas.removeEventListener('mousemove',this.mouseMove);
                this.$.mainCanvas.removeEventListener('mouseup',this.mouseEnd);
                this.$.mainCanvas.addEventListener('mousedown',this.mouseStart);
                this.$.mainCanvas.addEventListener('touchstart',this.touchStart);
                this.dispatch('moveSequence','MOVE','canvas','tumbleEnd', e.clientX, e.clientY);

            },

            _touchEnd: function(e){
                this._PreventMouseBubbling(e);
                if(e.targetTouches.length == 0){
                    this.$.mainCanvas.removeEventListener('touchmove',this.touchMove);
                    this.$.mainCanvas.removeEventListener('touchend',this.touchEnd);
                    this.$.mainCanvas.addEventListener('mousedown',this.mouseStart);
                    this.$.mainCanvas.addEventListener('touchstart',this.touchStart);
                    this.dispatch('moveSequence','MOVE','canvas','translateEnd', e.changedTouches[0].clientX, e.changedTouches[0].clientY);
                } else if (e.targetTouches.length == 1) {
                    this.dispatch('moveSequence','MOVE','canvas','pinchEnd', e.changedTouches[0].clientX, e.changedTouches[0].clientY);
                }

            },
            _PreventMouseBubbling: function (e) {
                e.preventDefault();
                e.stopPropagation();
                return false;
            }

        })
    </script>
</dom-module>

the bound component:

<link rel="import" href="bower_components/polymer/polymer.html">
<link rel="import" href="redux-store.html">

<dom-module id="ip-engine">

    <template>

    </template>
    <script>
        Polymer({
            is: "ip-engine",
            behaviors: [ ReduxBehavior ],
            properties: {
                trigger: {
                    type: Boolean,
                    value: true,
                    statePath: 'components.engine.trigger',
                    observer: '_sendCommand'
                },
                originator: {
                    type:String,
                    statePath: 'components.engine.originator'
                },
                command: {
                    type:String,
                    statePath: 'components.engine.command'
                },
                deltaX: {
                    type: Number,
                    statePath: 'components.engine.deltaX'
                },
                deltaY: {
                    type: Number,
                    statePath: 'components.engine.deltaY'
                },
                counter: {
                    type: Number,
                    value:''
                }
            },

            _sendCommand: function(){
                this.async(()=>{
                    console.log(this.originator + '  ' + this.command + '  ' + this.deltaX + '  ' + this.deltaY);
                });
            }

        })
    </script>
</dom-module>

thanks in advance

**Comment by tur-nr** [comment]
Read how [`combineReducers`](http://redux.js.org/docs/api/combineReducers.html) works.

> The shape of the state object matches the keys of the passed reducers.

So I'm guessing this is happening:

_State from single Reducer_
```js
{
    components:{
        canvas: {
            a:5
        },
        engine: {
            originator: '',
            command: '',
            deltaX: '',
            deltaY: '',
            trigger: true
        }
    }
}
```

_State from COMBINED Reducer_
```js
{
    reducer: {
        components:{
            canvas: {
                a:5
            },
            engine: {
                originator: '',
                command: '',
                deltaX: '',
                deltaY: '',
                trigger: true
            }
        }
    }
}
```

Hence your properties `statePath` does not map to the correct keys.

**Comment by benzile** [comment]
oh... i see, very well, now its working!
thank you very much for your help and for this great library
