### ISSUE TITLE
redux selector

### ISSUE THREAD

**Issue by togonow** [tur-nr/polymer-redux#88]
Is there a working example for using redux selector? 
i’m having issues adding reselect selectors to polymer 1 store

**Comment by tur-nr** [comment]
https://github.com/tur-nr/polymer-redux/blob/develop/v0/demo/selectors.html

**Comment by togonow** [comment]
I'm using polymer 1.9 will selectors work with the same way with 0.4.2?

**Comment by tur-nr** [comment]
Selectors should work on 1.9 as they are just pure functions that accept state, this works with the `statePath` function.

**Comment by togonow** [comment]
for some reason, selectors are not accessible from polymer elements here's the pattern i'm using:
`in the store:

    const store = Redux.createStore(reducer);
    store.subscribe(() => {
        console.log('store: ', store.getState(), store.getState().subtotal);
    });
    const ReduxBehavior = PolymerRedux(store);
var getItems = function getItems(state) {
        return state.items;
    };

    var totalItemsSelector = Reselect.createSelector(getItems, function (getItems) {
        return getItems.length;
    });


in the element properties:
      Polymer({
        is: 'cart',
        behaviors: [ReduxBehavior], /*jshint ignore: line */
        properties: {
           totalItemsSelector:{
            type: Number,
            statePath: 'totalItemsSelector'
          }
}
`

P.S. i'm able to pull properties from the store

**Comment by tur-nr** [comment]
`statePath` looks like you're passing a string constant. You must give the actual function reference.

**Comment by togonow** [comment]
oops, didn't notice the difference from the other statePath. Thanks a lot, it works.

**Comment by rkief** [comment]
I have been using selectors in this manner.  Seems to work very well.

Group them by type and import them as needed.
<link rel="import" href="../redux/actions/ElementActions.html">
<link rel="import" href="../redux/selectors/AccountSelectors.html">
<link rel="import" href="../redux/selectors/ElementSelectors.html">
<link rel="import" href="../redux/redux-store.html">
<link rel="import" href="../app-icons.html">
<link rel="import" href="../styles/shared-styles.html">

Add statepath to properties:
static get properties() {
        return {
          summary: {
            type: Array,
            statePath: getSummaryAmounts,
            readOnly: true
          },
          contracts: {
            type: Array,
            statePath: getContractAmount,
            readOnly: true
          },
selector.html:
<script src="../../../node_modules/reselect/dist/reselect.js"></script>
<script>
  const getAccountsArray = Reselect.createSelector(
    stateAccounts,
    getElementInfo,
    (accounts, element) =>
      _.filter(_.values(accounts), { 'GMR025': (element) ? element.WAPRTS : '', 'GMPEC': 'L' })
  );

  const getContractAmount = Reselect.createSelector(
    stateContracts,
    (elements) =>
      _.reduce(elements, function (result, obj) {
        let pdaopn = accounting.unformat(obj.PDAOPN);
        let found = _.findIndex(result, ['GMAID', obj.PDAID]);
        if (found > -1) {
          result[found]['contracts'] += pdaopn;
        } else (
          result.push({ 'GMAID': obj.PDAID, 'contracts': pdaopn })
        )
        return result;
      }, [])
  );

In the redux store I have the generic access to states:
  const stateShell = state => state.shell;
  const stateAccounts = state => state.accounts.accounts;
  const stateBrowse = state => state.browse;
  const stateBrowseFiltered = state => state.browse.filtered;

**Comment by tur-nr** [comment]
@rkief yes I agree, keeping selectors outside your Element definition is good practice. Separation of concerns and testability are two main advantages 👍

**Comment by rkief** [comment]
Sorry learning how to work the posts:
Here are screen shots.
![imports](https://user-images.githubusercontent.com/6942327/27161462-918d2f92-5149-11e7-941a-80aa8b2e1a7a.PNG)
![selector](https://user-images.githubusercontent.com/6942327/27161461-918cc3a4-5149-11e7-82da-410773d97de6.PNG)
![store](https://user-images.githubusercontent.com/6942327/27161460-918c39de-5149-11e7-8775-d471f493a553.PNG)
![element](https://user-images.githubusercontent.com/6942327/27161463-918db62e-5149-11e7-8b38-dfb9c44ff8e9.PNG)
