### ISSUE TITLE
..has "notify" enabled...

### ISSUE THREAD

**Issue by 0b1kn00b** [tur-nr/polymer-redux#9]
Could you remove this in the case where { readOnly  : true } in the properties declaration?

**Comment by 0b1kn00b** [comment]
except this I guess...
https://github.com/Polymer/polymer/issues/3551

**Comment by tur-nr** [comment]
@0b1kn00b check out #10 

There is a scenario when the element and store will become out of sync.

```javascript
demo._setName('Batman');
console.assert(demo.name === store.name); // Assertion failed
```

**Comment by 0b1kn00b** [comment]
Thanks for the heads up. Will keep it in mind.
