### ISSUE TITLE
Usage with Webpack: Module not found after install with yarn

### ISSUE THREAD

**Issue by robotgryphon** [tur-nr/polymer-redux#95]
Installed the package with yarn as `polymer-redux`, everything looks correct. Webpack immediately complains it cannot resolve 'polymer-redux'.

```
./scripts/site-state.html
Module not found: Error: Can't resolve 'polymer-redux' in 'C:\Users\---\Desktop\bioan\client\scripts'
 @ ./scripts/bioan-state.html 6:0-41
 @ ./bioan-app.html
 @ ./entry.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 ./entry.js
```

```
<!-- <link rel="import" href="../bower_components/polymer-redux/polymer-redux.html"> -->

<script>
    import { createStore, compose } from 'redux';
    import PolymerRedux from 'polymer-redux';

    console.log("Creating store");

    const initialState = { *** SNIP *** }
    const reducer = (state, action) => {  ** SNIP** }

    console.log("Creating Bioan.State mixin..");
    const store = createStore(reducer, initialState, compose(window.devToolsExtension ? window.devToolsExtension() : f => f));
    Bioan = Object.assign({}, window.Bioan || {}, { State: PolymerRedux(store) });
</script>
```

**Comment by tur-nr** [comment]
Try updating to v1.0.2. The updates from #94 were not published. You can also set your webpack resolve field to use the 'jsnext:main'.

**Comment by moebiusmania** [comment]
@robotgryphon hmmm don't know if HTML modules and ES modules syntax works fine together nested in each other (maybe they do but I'm unaware of that), if you want to use it with Webpack and Yarn it would be better to work only to ES modules, you can add support to HTML modules with loaders like wc-loader , but without nesting.
