### ISSUE TITLE
Kevin Schaaf Redux Implementation

### ISSUE THREAD

**Issue by Skeec** [tur-nr/polymer-redux#96]
I think subclassing like Kevin Schaaf did it in his presentation https://youtu.be/0A-2BhEZiM4?t=24m seems way more intuitive. Could you watch that and elaborate a little bit where this library makes it impossible to go this way or your choices in implementing it like you did?

Thanks
Skeec

**Comment by tur-nr** [comment]
https://gist.github.com/kevinpschaaf/995c9d1fd0f58fe021b174c4238b38c3#gistcomment-2187639
