### ISSUE TITLE
Redux-debounced support

### ISSUE THREAD

**Issue by chiefcll** [tur-nr/polymer-redux#98]
https://www.npmjs.com/package/redux-debounced

I'm trying to use redux-debounced which doesn't work due to how polymer-redux proxies the calls to dispatch. Redux debounced is looking for a meta key off of the function, this doesn't work due to https://github.com/tur-nr/polymer-redux/blob/master/src/index.js#L180-L190. Which copies the function removing the meta object that I add.

`
export function trackCustomerSearch(key) {
  const thunk = dispatch => {
    console.log('Search Key ----> ', key);
  };
  thunk.meta = {
    debounce: {
      time: 2500,
      key: 'TRACK_CUSTOMER_SEARCH'
    }
  };
  return thunk;
}
`

My additional question is why is polymer-redux doing that? Is redux-thunk not needed due to those lines? I'd prefer to just use redux-thunk so other redux middlewares will work as expected.

**Comment by tur-nr** [comment]
The reasons behind the proxy was to expose the action creators defined on the Element into the thunk's dispatch. This allows `dispatch('actionName')` from within the thunk.

I think copying properties onto the thunk will work, this will allow you to use debounced as intended.

**Comment by chiefcll** [comment]
I see - I would argue that you should remove it. Polymer-redux exposes the redux store + actionCreators to polymer. It makes it easy to call an actionCreators with `dispatch('actionName')` - but once you do redux should take over. Action creators should have access to its own actionCreators - by allowing your shortcut that makes redux tightly coupled to polymer redux. 

Redux should be its own independent layer. Copying properties would solve the bug, but it feels wrong. If you decide to do that please add some additional comments including why that other function is there. Thanks

**Comment by tur-nr** [comment]
I see, it's a valid point. I wanted to create a consistent interface with Redux in Polymer, but still the main focus was to use it without any complication, including middleware, which this has caused.

So to achieve consistency with action creators but allow Redux to do it's thing, we can do the following:

- [ ] Remove the dispatch proxy.
- [ ] Document the new way of action creators to dispatch actions, _see example_.
- [ ] Update to a major release since this will be a breaking change.

_Example of use action creators_

```js
class MyElement extends PolymerRedux(Polymer.Element) {
    static get actions() {
        return {
            foo() {
                return dispatch => {
                    dispatch(this.bar()); // this.bar() instead of dispatch('bar');
                };
            },
            bar() {
                return {
                    type: 'ACTION'
                };
            }
        };
}
```

Continuing with version 1.x of polymer-redux, copying the properties will help you overcome this issue.

How does this seem moving forward?

**Comment by chiefcll** [comment]
👍 

Plan moving forward is good. With the 2.0 version I'd recommend you emphasize the decoupling of redux from Polymer Redux. Having your action creators in Polymer components creates a tight coupling. We like to have the redux layer be reusable with any frontend framework. We do that like this:

```
import actions from '../redux/actionCreators.js';
let PolymerReduxMixin = PolymerRedux(store);
const ReduxMixin = function(Base) {
    return class ReduxActions extends PolymerReduxMixin(Base) {
      static get actions() {
        return actions;
      }

      get actions() {
        return actions;
      }
    };
  };
```
This exposes all the actionCreators to polymer components so they can do `this.dispatch(this.actions.bar())`.

**Comment by chiefcll** [comment]
And it may even be better to do

```javascript
import actions from '../redux/actionCreators.js';
let PolymerReduxMixin = PolymerRedux(store, actions);
```

Where actions is an object of `{'MY_ACTION_CREATOR': function()}`
